### ISSUE TITLE
Errors searching by Payload CID

### ISSUE THREAD

**Issue by s0nik42** [protofire/filecoin-CID-checker#81]
Hello, I notice a bug on the website. I noticed we can search by Payload CID, when the Payload contains special characters like a “/” it doesn’t work :
Do WORK :
“mAXCg5AIgtVZ8av5dvKsSPhWvFuq0iJ6I9MSxY3M1ag+dlNw6frc”
Doesn’t WORK :
“mAXCg5AIgD89f0WMX+XSB/StGqKxt1HTwSP0RLvum8tVX+pav/10”

**Comment by unjapones** [comment]
@s0nik42 the PR https://github.com/Digital-MOB-Filecoin/filecoin-CID-checker/pull/3 should fix this but it also needs some infra/devops work in order to deploy the corresponding changes

Already commented in there if there is a chance to merge & deploy this. I'll be out on vacation but the people involved may be able to manage this.

cc @vschernoff @ArseniiPetrovich @smooth-operator

**Comment by ArseniiPetrovich** [comment]
@s0nik42 This issue is solved now and the bugfix is installed into the production server. Please, check on your end :)
